// module-3/week-1/day-4/react-router/src/components/nav/NavMain.jsx
import React from "react";
import { NavLink } from "react-router-dom";

export default function NavMain() {
  return (
    <nav id="nav-main">
      <NavLink exact to="/">Home |</NavLink>
      <NavLink to="/about">About |</NavLink>
      <NavLink to="/contact">contact |</NavLink>
    </nav>
  );
}

// module-3/week-3/day-3/vue-burger/src/components/NavMain.vue
<template>
  <nav id="nav-main">
    <router-link to="/">Home</router-link>|
    <router-link to="/about">About</router-link>
    <IconBurger />
  </nav>
</template>

<script>
import IconBurger from "@/components/IconBurger";

export default {
  components: {
    IconBurger
  }
};
</script>

<style></style>
